import localFont from "next/font/local";
import "./globals.css";
import Nav from "./components/Nav";
import { SearchProvider } from "./context/SearchContext";
import { BasketProvider } from "./context/BasketContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BasketProvider>
        <SearchProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1700px] flex flex-col justify-center mx-auto`}
          >
            <Nav />
            {children}
          </body>
        </SearchProvider>
      </BasketProvider>
    </html>
  );
}
